# Generated by Django 4.2.2 on 2023-06-22 06:46

from django.db import migrations, models
import searchapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='full_details',
            field=models.TextField(validators=[searchapp.models.validate_json]),
        ),
        migrations.AlterField(
            model_name='dish',
            name='items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
